[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Home"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Home"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "End"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "End"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001B[5;2~"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[5;5~"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[5~"
key = "PageUp"

[[keyboard.bindings]]
chars = "\u001B[6;2~"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u007F"
key = "Delete"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u0018,"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0000"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018)"
key = "N"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018)"
key = "N"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u0018("
key = "P"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018("
key = "P"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u0018C"
key = "T"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018C"
key = "T"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u0018$"
key = "R"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018$"
key = "R"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u0018<"
key = "Comma"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u0018>"
key = "Period"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u001B,"
key = "Comma"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018m"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018b"
key = "K"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018d"
key = "X"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018v"
key = "V"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018s"
key = "A"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018V"
key = "S"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018\b"
key = "H"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018\u001b"
key = "J"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018\u000B"
key = "K"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018\f"
key = "L"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u00181"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00182"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00183"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00184"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00185"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00186"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00187"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00188"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00189"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018x"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018w"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018/"
key = "Slash"
mods = "Control|Command"

[[keyboard.bindings]]
chars = "\u0018,"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018["
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018="
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018o"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018z"
key = "O"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018z"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018\u0001"
key = "Escape"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018\u0010"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018\u000E"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018\t"
key = "F"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018\t"
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018n"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018p"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018/"
key = "Slash"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018!"
key = "I"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018$"
key = "I"
mods = "Shift|Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018m"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018b"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018d"
key = "X"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u0018v"
key = "V"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u0018s"
key = "A"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u0018V"
key = "S"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u0018\b"
key = "H"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = """
\u0018
"""
key = "J"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u0018\u000B"
key = "K"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u0018\f"
key = "L"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u00181"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00182"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00183"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00184"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00185"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00186"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00187"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00188"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00189"
key = "Key9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018c"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018x"
key = "X"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018w"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018/"
key = "Slash"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u0018,"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018["
key = "LBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018="
key = "A"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018o"
key = "O"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018z"
key = "O"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u0018z"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018\u0001"
key = "Escape"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018<"
key = "Comma"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018>"
key = "Period"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018\u0010"
key = "Comma"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018\u000E"
key = "Semicolon"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018\t"
key = "F"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u0018\t"
key = "E"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018n"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018p"
key = "P"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018/"
key = "Slash"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018!"
key = "I"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018$"
key = "I"
mods = "Shift|Alt"

[window]
option_as_alt = "Both"
# decorations = "Buttonless"
opacity = 1

[window.padding]
x = 5
y = 5

[colors.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.footer_bar]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.normal]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[colors.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"

[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[[colors.indexed_colors]]
index = 16
color = "#FAB387"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"
